import type { IntelItem } from "./types";

/**
 * Sample data mirroring the design mockup. This is a stand-in for the
 * community intel API — see intel-source.ts for the integration seam.
 * Facet fields (threatActors, vulnerabilities, malware, mitre) are populated
 * so the faceted sidebar is exercisable end to end.
 */
export const MOCK_INTEL: IntelItem[] = [
  {
    id: "1",
    slug: "inf0s3c-python-stealer",
    title: "Unveiling a Python Stealer — INF0S3C Stealer",
    description:
      "New Python-based infostealer harvests browser credentials, crypto wallets, and Discord tokens via PyInstaller-packed binaries.",
    type: "Intel Report",
    source: "Unit 42",
    contributor: "sigmahq",
    updatedAt: "2026-05-27T09:00:00Z",
    aiEnriched: true,
    malware: ["INF0S3C Stealer"],
    mitre: ["T1059", "T1555"],
  },
  {
    id: "2",
    slug: "sitecore-cache-poisoning-rce",
    title: "Cache Me If You Can: Sitecore Experience Platform Cache Poisoning to RCE",
    description:
      "Cache poisoning vulnerability in Sitecore XP enables unauthenticated remote code execution on default deployments.",
    type: "Intel Report",
    source: "Mandiant",
    contributor: "dheerajpai",
    updatedAt: "2026-05-27T06:00:00Z",
    vulnerabilities: ["CVE-2025-53690"],
    mitre: ["T1190"],
  },
  {
    id: "3",
    slug: "apt29-diplomatic-espionage",
    title: "APT29 — Renewed Espionage Targeting Diplomatic Networks",
    description:
      "Cozy Bear's 2026 campaign uses refreshed WINELOADER variants and EnvyScout dropper to compromise ministries across Europe.",
    type: "Intel Report",
    source: "CrowdStrike",
    contributor: "anvilogic",
    updatedAt: "2026-05-27T03:00:00Z",
    aiEnriched: true,
    threatActors: ["APT29"],
    malware: ["WINELOADER", "EnvyScout"],
    mitre: ["T1566"],
  },
  {
    id: "4",
    slug: "three-lazarus-rats",
    title: "Three Lazarus RATs Coming For Your Cheese",
    description:
      "DPRK-aligned Lazarus Group deploys three previously undocumented remote access trojans targeting financial sector.",
    type: "Intel Report",
    source: "Microsoft",
    contributor: "govind_s2s",
    updatedAt: "2026-05-27T00:00:00Z",
    threatActors: ["Lazarus Group"],
    mitre: ["T1059"],
  },
  {
    id: "5",
    slug: "golden-dmsa-abuse",
    title: "Golden dMSA — Delegated Managed Service Account Abuse",
    description:
      "Novel post-exploitation technique abusing Windows Server 2025 dMSAs for persistent privileged access in Active Directory.",
    type: "Intel Report",
    source: "Mandiant",
    contributor: "slimkql",
    updatedAt: "2026-05-26T11:00:00Z",
    aiEnriched: true,
    mitre: ["T1078"],
  },
  {
    id: "6",
    slug: "rapperbot-infection-to-ddos",
    title: "RapperBot: From Infection to DDoS in a Split Second",
    description:
      "IoT botnet evolution shows accelerated time-to-attack via embedded SSH brute force and reflection capabilities.",
    type: "Article",
    source: "Cisco Talos",
    contributor: "reversinglabs",
    updatedAt: "2026-05-26T08:00:00Z",
    malware: ["RapperBot"],
    mitre: ["T1078"],
  },
  {
    id: "7",
    slug: "stealerium-phantom-infostealers",
    title: "Not Safe For Work: Tracking Stealerium and Phantom Infostealers",
    description:
      "Two infostealer families using NSFW-themed lures and screenshot capture for sensitive document exfiltration.",
    type: "Intel Report",
    source: "Recorded Future",
    contributor: "bertjan",
    updatedAt: "2026-05-25T08:00:00Z",
    malware: ["Stealerium", "Phantom Stealer"],
    mitre: ["T1566"],
  },
  {
    id: "8",
    slug: "obscura-ransomware",
    title: "Obscura, an Obscure New Ransomware Variant",
    description:
      "New ransomware family using ChaCha20 encryption and Tor-based negotiation portal targeting mid-market organizations.",
    type: "Intel Report",
    source: "Unit 42",
    contributor: "nish",
    updatedAt: "2026-05-25T05:00:00Z",
    malware: ["Obscura"],
  },
  {
    id: "9",
    slug: "dire-wolf-ransomware",
    title: "Dire Wolf Ransomware: Data Encryption and Leak Extortion",
    description:
      "Double-extortion ransomware targeting healthcare and education with custom .NET locker and 14-day leak countdown.",
    type: "Advisory",
    source: "CrowdStrike",
    contributor: "jamesmuir",
    updatedAt: "2026-05-24T12:00:00Z",
    aiEnriched: true,
    malware: ["Dire Wolf"],
  },
  {
    id: "10",
    slug: "amos-stealer-macos-cracked-apps",
    title: "An MDR Analysis of the AMOS Stealer Campaign Targeting macOS via 'Cracked' Apps",
    description:
      "AMOS stealer distribution via cracked software repositories. New persistence mechanism using LaunchAgents.",
    type: "Intel Report",
    source: "Microsoft",
    contributor: "kqlwizard",
    updatedAt: "2026-05-24T09:00:00Z",
    malware: ["AMOS Stealer"],
    mitre: ["T1059"],
  },
  {
    id: "11",
    slug: "darkvision-rat-sandbox",
    title: "Darkvision RAT — any.run Sandbox Analysis",
    description:
      "Sandbox-extracted IoCs and behavioral signatures for Darkvision remote access trojan delivered via malicious PDF.",
    type: "Blog Post",
    source: "Any.Run",
    contributor: "sigmadetectionrules",
    updatedAt: "2026-05-23T09:00:00Z",
    malware: ["Darkvision RAT"],
    mitre: ["T1566"],
  },
  {
    id: "12",
    slug: "apt-financial-attacks-q2-2025",
    title: "APT and Financial Attacks on Industrial Organizations in Q2 2025",
    description:
      "Quarterly intel review covering 14 active campaigns against energy, manufacturing, and water utilities sectors.",
    type: "Threat Brief",
    source: "Kaspersky",
    contributor: "mfrancess",
    updatedAt: "2026-05-23T06:00:00Z",
    aiEnriched: true,
    threatActors: ["FIN7"],
  },
  {
    id: "13",
    slug: "salat-stealer-deep-dive",
    title: "Unmasked: Salat Stealer — Deep Dive into Persistence and C2",
    description:
      "Detailed reverse-engineering of Salat Stealer's WMI persistence and HTTPS-based C2 infrastructure.",
    type: "Intel Report",
    source: "Mandiant",
    contributor: "shsameer",
    updatedAt: "2026-05-22T09:00:00Z",
    malware: ["Salat Stealer"],
    mitre: ["T1059"],
  },
  {
    id: "14",
    slug: "nightshadec2-botnet",
    title: "NightshadeC2 — New Botnet Emerges from the Shadows",
    description:
      "Multi-platform botnet with novel domain generation algorithm and modular plugin architecture.",
    type: "Intel Report",
    source: "Unit 42",
    contributor: "joesecurity",
    updatedAt: "2026-05-22T06:00:00Z",
    malware: ["NightshadeC2"],
  },
  {
    id: "15",
    slug: "python-supply-chain-termncolor",
    title: "Supply Chain Risk in Python: Termncolor and Colorinal Explained",
    description:
      "Two malicious PyPI packages exfiltrate credentials via typosquat attacks. 48 victim organizations identified.",
    type: "Article",
    source: "Cisco Talos",
    contributor: "aaronmogs2s",
    updatedAt: "2026-05-21T09:00:00Z",
    mitre: ["T1190"],
  },
  {
    id: "16",
    slug: "sitecore-viewstate-zeroday",
    title: "ViewState Deserialization Zero-Day in Sitecore (CVE-2025-53690)",
    description:
      "Active exploitation of unpatched Sitecore ViewState deserialization leading to RCE. Detection guidance included.",
    type: "Advisory",
    source: "Microsoft",
    contributor: "shiftyroot",
    updatedAt: "2026-05-20T09:00:00Z",
    aiEnriched: true,
    vulnerabilities: ["CVE-2025-53690"],
    mitre: ["T1190"],
  },
  {
    id: "17",
    slug: "mostererat-anydesk-tightvnc",
    title: "MostereRAT Deployed AnyDesk and TightVNC for Covert Full Access",
    description:
      "RAT operators bundle legitimate remote-access tools to bypass EDR and maintain hidden persistence.",
    type: "Intel Report",
    source: "Mandiant",
    contributor: "timpeck",
    updatedAt: "2026-05-20T06:00:00Z",
    malware: ["MostereRAT"],
    mitre: ["T1078"],
  },
  {
    id: "18",
    slug: "apt37-rust-backdoor",
    title: "APT37 Targets Windows with Rust Backdoor and Python Loader",
    description:
      "DPRK-linked APT37 introduces Rust-based backdoor with multi-stage Python loader for stealth and EDR evasion.",
    type: "Intel Report",
    source: "Recorded Future",
    contributor: "iamsubashg",
    updatedAt: "2026-05-20T03:00:00Z",
    threatActors: ["APT37"],
    mitre: ["T1059"],
  },
  {
    id: "19",
    slug: "ransomware-gang-connections",
    title: "Blurring the Lines: Intrusion Shows Connection Between Three Major Ransomware Gangs",
    description:
      "Analysis of toolkit reuse and infrastructure overlap among Black Basta, RansomHub, and BlackSuit operations.",
    type: "Intel Report",
    source: "Unit 42",
    contributor: "kchoy",
    updatedAt: "2026-05-19T09:00:00Z",
    mitre: ["T1078"],
  },
  {
    id: "20",
    slug: "lunobotnet-self-healing-linux",
    title: "LunoBotnet: A Self-Healing Linux Botnet with Modular DDoS and Cryptojacking",
    description:
      "Newly discovered Linux botnet uses heartbeat-based self-healing and runtime module loading for resilience.",
    type: "Intel Report",
    source: "CrowdStrike",
    contributor: "100daysofyara",
    updatedAt: "2026-05-13T09:00:00Z",
    aiEnriched: true,
    malware: ["LunoBotnet"],
  },
];
