/**
 * @generated
 * @file DropdownSample (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";
import List from "../webflow_modules/Basic/components/List";
import ListItem from "../webflow_modules/Basic/components/ListItem";

/**
 * DropdownSample
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function DropdownSample({ classProp = "is-desktop" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <List
        className={"nav_dropdown_list"}
        id={"w-node-_6600db68-641e-b95b-9150-11472687959c-2687959c"}
        tag={"ul"}
        unstyled={false}
      >
        <ListItem className={"nav_dropdown_item"}>
          <Link
            block={"inline"}
            button={false}
            className={"nav_dropdown_link"}
            options={{
              href: "#",
            }}
          >
            <Block className={"menu_icon_wrap"} tag={"div"}>
              <DOM
                className={"icon-tiny"}
                fill={"none"}
                tag={"svg"}
                viewBox={"0 0 100 100"}
                width={"100%"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <DOM clip-path={"url(#clip0_1070_175)"} tag={"g"}>
                  <DOM
                    d={
                      "M69.2308 0C67.1124 0 65.3846 1.72777 65.3846 3.84615V9.85577L34.6154 44.4712V34.6154C34.6154 32.497 32.8876 30.7692 30.7692 30.7692H3.84615C1.72777 30.7692 0 32.497 0 34.6154V65.3846C0 67.503 1.72777 69.2308 3.84615 69.2308H30.7692C32.8876 69.2308 34.6154 67.503 34.6154 65.3846V55.7692L65.3846 89.9038V96.1538C65.3846 98.2722 67.1124 100 69.2308 100H96.1538C98.2722 100 100 98.2722 100 96.1538V73.0769C100 70.9585 98.2722 69.2308 96.1538 69.2308H69.2308C67.1124 69.2308 65.3846 70.9585 65.3846 73.0769V78.4856L39.9038 50.1202L65.3846 21.3942V26.9231C65.3846 29.0415 67.1124 30.7692 69.2308 30.7692H96.1538C98.2722 30.7692 100 29.0415 100 26.9231V3.84615C100 1.72777 98.2722 0 96.1538 0H69.2308Z"
                    }
                    fill={"currentColor"}
                    tag={"path"}
                  />
                </DOM>
                <DOM tag={"defs"}>
                  <DOM id={"clip0_1070_175"} tag={"clippath"}>
                    <DOM
                      fill={"currentColor"}
                      height={"100"}
                      tag={"rect"}
                      width={"100"}
                    />
                  </DOM>
                </DOM>
              </DOM>
            </Block>
            <Block className={"menu_content"} tag={"div"}>
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Lorem ipsum"}
              </Block>
              <Block
                className={"nav_dropdown_text text-color-faded text-size-tiny"}
                tag={"div"}
              >
                {"Lorem Ipsu Dolor Sit Ament"}
              </Block>
            </Block>
          </Link>
        </ListItem>
        <ListItem className={"nav_dropdown_item"}>
          <Link
            block={"inline"}
            button={false}
            className={"nav_dropdown_link"}
            options={{
              href: "#",
            }}
          >
            <Block className={"menu_icon_wrap"} tag={"div"}>
              <DOM
                className={"icon-tiny"}
                fill={"none"}
                tag={"svg"}
                viewBox={"0 0 100 100"}
                width={"100%"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <DOM
                  d={
                    "M25.0003 12.5001C24.4482 12.4922 23.9 12.5942 23.3876 12.8001C22.8753 13.006 22.4089 13.3117 22.0157 13.6994C21.6225 14.0871 21.3103 14.549 21.0972 15.0584C20.8841 15.5678 20.7743 16.1145 20.7743 16.6667C20.7743 17.2189 20.8841 17.7656 21.0972 18.275C21.3103 18.7844 21.6225 19.2464 22.0157 19.6341C22.4089 20.0217 22.8753 20.3274 23.3876 20.5333C23.9 20.7392 24.4482 20.8412 25.0003 20.8334H83.3337V66.6667C83.3258 67.2188 83.4279 67.767 83.6337 68.2794C83.8396 68.7918 84.1453 69.2581 84.533 69.6513C84.9207 70.0445 85.3826 70.3568 85.892 70.5699C86.4015 70.783 86.9481 70.8927 87.5003 70.8927C88.0525 70.8927 88.5992 70.783 89.1086 70.5699C89.618 70.3568 90.08 70.0445 90.4677 69.6513C90.8553 69.2581 91.161 68.7918 91.3669 68.2794C91.5728 67.767 91.6748 67.2188 91.667 66.6667V20.8334C91.667 16.279 87.8881 12.5001 83.3337 12.5001H25.0003ZM12.5003 29.1667C7.90449 29.1667 4.16699 32.9042 4.16699 37.5001V79.1667C4.16699 83.7625 7.90449 87.5 12.5003 87.5H66.667C71.2628 87.5 75.0003 83.7625 75.0003 79.1667V37.5001C75.0003 32.9042 71.2628 29.1667 66.667 29.1667H12.5003Z"
                  }
                  fill={"currentColor"}
                  tag={"path"}
                />
              </DOM>
            </Block>
            <Block className={"menu_content"} tag={"div"}>
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Lorem ipsum"}
              </Block>
              <Block
                className={"nav_dropdown_text text-color-faded text-size-tiny"}
                tag={"div"}
              >
                {"Lorem Ipsu Dolor Sit Ament"}
              </Block>
            </Block>
          </Link>
        </ListItem>
        <ListItem className={"nav_dropdown_item"}>
          <Link
            block={"inline"}
            button={false}
            className={"nav_dropdown_link"}
            options={{
              href: "#",
            }}
          >
            <Block className={"menu_icon_wrap"} tag={"div"}>
              <DOM
                className={"icon-tiny"}
                fill={"none"}
                tag={"svg"}
                viewBox={"0 0 100 100"}
                width={"100%"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <DOM
                  d={
                    "M25.0003 12.5001C24.4482 12.4922 23.9 12.5942 23.3876 12.8001C22.8753 13.006 22.4089 13.3117 22.0157 13.6994C21.6225 14.0871 21.3103 14.549 21.0972 15.0584C20.8841 15.5678 20.7743 16.1145 20.7743 16.6667C20.7743 17.2189 20.8841 17.7656 21.0972 18.275C21.3103 18.7844 21.6225 19.2464 22.0157 19.6341C22.4089 20.0217 22.8753 20.3274 23.3876 20.5333C23.9 20.7392 24.4482 20.8412 25.0003 20.8334H83.3337V66.6667C83.3258 67.2188 83.4279 67.767 83.6337 68.2794C83.8396 68.7918 84.1453 69.2581 84.533 69.6513C84.9207 70.0445 85.3826 70.3568 85.892 70.5699C86.4015 70.783 86.9481 70.8927 87.5003 70.8927C88.0525 70.8927 88.5992 70.783 89.1086 70.5699C89.618 70.3568 90.08 70.0445 90.4677 69.6513C90.8553 69.2581 91.161 68.7918 91.3669 68.2794C91.5728 67.767 91.6748 67.2188 91.667 66.6667V20.8334C91.667 16.279 87.8881 12.5001 83.3337 12.5001H25.0003ZM12.5003 29.1667C7.90449 29.1667 4.16699 32.9042 4.16699 37.5001V79.1667C4.16699 83.7625 7.90449 87.5 12.5003 87.5H66.667C71.2628 87.5 75.0003 83.7625 75.0003 79.1667V37.5001C75.0003 32.9042 71.2628 29.1667 66.667 29.1667H12.5003Z"
                  }
                  fill={"currentColor"}
                  tag={"path"}
                />
              </DOM>
            </Block>
            <Block className={"menu_content"} tag={"div"}>
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Integrations"}
              </Block>
              <Block
                className={"nav_dropdown_text text-color-faded text-size-tiny"}
                tag={"div"}
              >
                {"Lorem Ipsu Dolor Sit Ament"}
              </Block>
            </Block>
          </Link>
        </ListItem>
      </List>
    </div>
  );
}
