/**
 * @generated
 * @file NavLinksComponent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import DropdownList from "../webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "../webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../webflow_modules/Dropdown/components/DropdownWrapper";
import Link from "../webflow_modules/Basic/components/Link";
import List from "../webflow_modules/Basic/components/List";
import ListItem from "../webflow_modules/Basic/components/ListItem";
import { BasicButton } from "../buttons/BasicButton";
import { DropdownSample } from "./DropdownSample";

/**
 * NavLinksComponent
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function NavLinksComponent({
  dropdownSample1Class = "is-desktop",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Desktop: "w-variant-feaca499-f549-4a5d-8393-8c3f4fa32b38",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`nav_links_component ${_activeStyleVariant}`}
        tag={"div"}
      >
        <List
          className={`nav_links_wrap ${_activeStyleVariant}`}
          tag={"ul"}
          unstyled={true}
        >
          <ListItem className={`nav_links_item ${_activeStyleVariant}`}>
            <DropdownWrapper
              className={`nav_dropdown_component ${_activeStyleVariant}`}
              delay={400}
              hover={true}
              tag={"div"}
            >
              <DropdownList
                className={`nav_dropdown_main_wrap ${_activeStyleVariant}`}
                tag={"nav"}
              >
                <Block
                  className={`nav_dropdown_main_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav_dropdown_main_scroll ${_activeStyleVariant}`}
                    data-lenis-prevent={""}
                    tag={"div"}
                  >
                    <DropdownSample classProp={dropdownSample1Class} />
                  </Block>
                </Block>
              </DropdownList>
            </DropdownWrapper>
          </ListItem>
          <ListItem className={`nav_links_item ${_activeStyleVariant}`}>
            <DropdownWrapper
              className={`nav_dropdown_component ${_activeStyleVariant}`}
              delay={250}
              hover={true}
              tag={"div"}
            >
              <DropdownToggle
                className={`nav_links_link ${_activeStyleVariant}`}
                data-trigger={"hover focus"}
                tag={"div"}
              >
                <Block
                  className={`nav_links_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Resources"}
                </Block>
                <DOM
                  aria-hidden={"true"}
                  className={`nav_links_svg desktop-32 ${_activeStyleVariant}`}
                  fill={"none"}
                  tag={"svg"}
                  viewBox={"0 0 47 24"}
                  width={"100%"}
                  xmlns={"http://www.w3.org/2000/svg"}
                >
                  <DOM
                    d={"M1 1L23.5 23L46 1"}
                    stroke={"currentColor"}
                    stroke-width={"var(--nav--icon-thickness)"}
                    tag={"path"}
                    vector-effect={"non-scaling-stroke"}
                  />
                </DOM>
              </DropdownToggle>
              <DropdownList
                className={`nav_dropdown_main_wrap ${_activeStyleVariant}`}
                tag={"nav"}
              >
                <Block
                  className={`nav_dropdown_main_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav_dropdown_main_scroll ${_activeStyleVariant}`}
                    data-lenis-prevent={""}
                    tag={"div"}
                  >
                    <DropdownSample classProp={dropdownSample1Class} />
                  </Block>
                </Block>
              </DropdownList>
            </DropdownWrapper>
          </ListItem>
          <ListItem className={`nav_links_item ${_activeStyleVariant}`}>
            <Link
              block={"inline"}
              button={false}
              className={`nav_links_link ${_activeStyleVariant}`}
              data-trigger={"hover focus"}
              options={{
                href: "/about",
              }}
            >
              <Block tag={"div"}>{"About"}</Block>
            </Link>
          </ListItem>
          <ListItem className={`nav_links_item ${_activeStyleVariant}`}>
            <Link
              block={"inline"}
              button={false}
              className={`nav_links_link ${_activeStyleVariant}`}
              data-trigger={"hover focus"}
              options={{
                href: "/leaderboard",
              }}
            >
              <Block tag={"div"}>{"Leaderboard"}</Block>
            </Link>
          </ListItem>
        </List>
        <List
          className={`nav_actions_wrap is-desktop ${_activeStyleVariant}`}
          tag={"ul"}
          unstyled={true}
        >
          <ListItem className={`nav_buttons_item mx-4 ${_activeStyleVariant}`}>
            <BasicButton
              buttonStyle={"Nav Secondary"}
              buttonText={"Request Code"}
            />
          </ListItem>
          <ListItem className={`nav_buttons_item ${_activeStyleVariant}`}>
            <BasicButton
              buttonStyle={"Nav"}
              buttonText={"Sign In"}
              globalClickableLink={{
                href: "/login",
              }}
              id={"login-link"}
            />
          </ListItem>
        </List>
      </Block>
    </div>
  );
}
