/**
 * @generated
 * @file NavMegaLayout (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";
import List from "../webflow_modules/Basic/components/List";
import ListItem from "../webflow_modules/Basic/components/ListItem";

/**
 * NavMegaLayout
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function NavMegaLayout({ classProp = "is-desktop" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"nav_dropdown_mega_layout"} tag={"div"}>
        <List className={"nav_dropdown_list"} tag={"ul"} unstyled={false}>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
        </List>
        <List className={"nav_dropdown_list"} tag={"ul"} unstyled={false}>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
        </List>
        <List className={"nav_dropdown_list"} tag={"ul"} unstyled={false}>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
          <ListItem className={"nav_dropdown_item"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_dropdown_link"}
              options={{
                href: "#",
              }}
            >
              <Block className={"nav_dropdown_text"} tag={"div"}>
                {"Branding"}
              </Block>
            </Link>
          </ListItem>
        </List>
      </Block>
    </div>
  );
}
