/**
 * @generated
 * @file Text (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import RichText from "../webflow_modules/Basic/components/RichText";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Text
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Text({
  customClass = "mb-1",
  maxWidth = -1,
  text = "",
  variant = "Text Size Main",
  visibility = true,
}) {
  const _styleVariantMap = {
    "Text Size Main": "",
    "Text Size Large": "w-variant-d1f8a31e-200a-31ea-8413-1a1d9579048a",
    "Text Size Small": "w-variant-c12058f6-417c-9a6d-715e-94c0e11b7eb9",
    H6: "w-variant-8047468b-814a-b283-1562-67d9f0fd24aa",
    H5: "w-variant-f4b0fcc8-dfb9-5d1b-798e-f1685ea99c78",
    H4: "w-variant-9bf223c8-d9b4-38f0-5032-99c9c84f9538",
    H3: "w-variant-c016e562-3b23-17da-a90d-5b381de60676",
    H2: "w-variant-8ea903ee-5ee2-a605-ece8-9873a29e0db2",
    H1: "w-variant-a85a4720-96a1-8d22-29ef-33d05433debb",
    Display: "w-variant-46a53ec1-3b63-8c00-297b-b272273eee4f",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <RichText
          className={`text ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          tag={"div"}
        >
          {text}
        </RichText>
      ) : null}
    </div>
  );
}
