/**
 * @generated
 * @file SectionCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Section from "../webflow_modules/Layout/components/Section";
import { BasicButton } from "../buttons/BasicButton";
import { ButtonGroup } from "../buttons/ButtonGroup";
import { ContentWrap } from "../layout/ContentWrap";
import { DitherSection } from "../DitherSection";
import { Eyebrow } from "../Eyebrow";
import { Header } from "../typography/Header";
import { IconUsers } from "../IconUsers";
import { SectionSpace } from "../layout/SectionSpace";
import { TextPlain } from "../TextPlain";

/**
 * SectionCta
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function SectionCta({
  contentWrapAlign = "Left",
  contentWrapClass = "margin-trim",
  contentWrapContentWrapperClass = "",
  contentWrapSpacingPaddingBottom = "none",
  contentWrapSpacingPaddingTop = "none",
  eyebrowClass = "mb-3",
  eyebrowText = "used by 12000+ engineers",
  eyebrowVariant = "Base",
  headerCustomClass = "mb-4",
  headerMaxWidth = 10,
  headerSize = "Display",
  headerText = "",
  headerVisibility = true,
  sectionSpace2Variant = "Medium",
  sectionSpaceVariant = "Small",
  textPlainClass = "",
  textPlainMaxWidth = 27,
  textPlainStyle = "",
  textPlainTag = "p",
  textPlainText = "Join the community that moves faster than the threat.",
  textPlainVariant = "Text Large",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section theme-dark overflow-clip"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <DitherSection
          classProp={"top-negative"}
          ditherColor={"#67655E"}
          variant={"Down"}
        />
        <Block className={"content_contain container-large"} tag={"div"}>
          <Block className={"content grid-custom"} tag={"div"}>
            <Block className={"cta_col column-7"} tag={"div"}>
              <SectionSpace variant={"Small"} />
              <ContentWrap
                align={contentWrapAlign}
                classProp={contentWrapClass}
                content={
                  <>
                    <Eyebrow
                      classProp={eyebrowClass}
                      icon={<IconUsers />}
                      text={eyebrowText}
                      variant={eyebrowVariant}
                    />
                    <Header
                      customClass={headerCustomClass}
                      maxWidth={headerMaxWidth}
                      size={headerSize}
                      text={headerText}
                      visibility={headerVisibility}
                    />
                    <TextPlain
                      classProp={textPlainClass}
                      maxWidth={textPlainMaxWidth}
                      style={textPlainStyle}
                      tag={textPlainTag}
                      text={textPlainText}
                      variant={textPlainVariant}
                    />
                  </>
                }
                contentWrapperClass={contentWrapContentWrapperClass}
                spacingPaddingBottom={contentWrapSpacingPaddingBottom}
                spacingPaddingTop={contentWrapSpacingPaddingTop}
              />
              <SectionSpace variant={"Small"} />
            </Block>
            <Block className={"cta_col border-sides column-4"} tag={"div"}>
              <Block className={"cta_content align-self-center"} tag={"div"}>
                <ButtonGroup
                  buttons={
                    <>
                      <BasicButton
                        buttonText={"Sign In"}
                        globalClickableLink={{
                          href: "/login",
                        }}
                      />
                      <BasicButton
                        buttonStyle={"Secondary"}
                        buttonText={"Get Started"}
                      />
                    </>
                  }
                />
              </Block>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
