/**
 * @generated
 * @file SectionMarquee (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * SectionMarquee
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function SectionMarquee({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"marquee-1_component"} tag={"div"}>
        <HtmlEmbed
          className={"marquee-1_embed"}
          content={
            "<style>\n@keyframes marquee-1-timeline {\n\tfrom { transform: translateX(0%); }\n\tto { transform: translateX(-50%); }\n}\n</style>"
          }
        />
        <Block className={"marquee-1_layout"} tag={"div"}>
          <Block className={"marquee-1_track is-reversed"} tag={"div"}>
            <NotSupported _atom={"Collection List"} />
            <NotSupported _atom={"Collection List"} />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
