/**
 * @generated
 * @file CmsMostLiked (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Image from "../webflow_modules/Basic/components/Image";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import { Eyebrow } from "../Eyebrow";
import { IconArrowsClockwise } from "../IconArrowsClockwise";
import { IconThumbsUp } from "../IconThumbsUp";
import { TextPlain } from "../TextPlain";

/**
 * CmsMostLiked
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Collection List Items`, `Empty State`
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function CmsMostLiked({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Collection List"}>
        <NotSupported _atom={"Collection List Items"} />
        <NotSupported _atom={"Empty State"} />
      </NotSupported>
    </div>
  );
}
