/**
 * @generated
 * @file BasicButton (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Clickable } from "../utils/Clickable";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { isSet } from "../webflow_modules/Text/helpers/isSet";
import { linkIsSet } from "../webflow_modules/Basic/helpers/linkIsSet";

/**
 * BasicButton
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function BasicButton({
  attributeAttributeValue = "",
  attributeDataAttributeName = "",
  buttonStyle = "Primary",
  buttonText = "Button Text",
  globalClickableAriaLabel = "",

  globalClickableLink = {
    href: "#",
  },

  globalClickableTargetUseBlankForANewWindow = "",
  globalClickableTypeButtonSubmitEtc = "",
  iconWrap,
  id = "",
}) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-342e86e2-406d-45ce-198c-2cddd0b8f7f3",
    Nav: "w-variant-e9595921-b417-4d70-e0fa-e69d1cda0925",
    "Nav Secondary": "w-variant-e580a473-fa4d-c6a0-2819-df024f042d8c",
    "Full Width": "w-variant-ebd5e63b-9b94-5aa4-12a6-19b11987860a",
  };

  const _activeStyleVariant = _styleVariantMap[buttonStyle];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        className={`g_button_main_wrap ${_activeStyleVariant}`}
        data-trigger={"hover focus"}
        id={id}
        tag={"div"}
      >
        <Block className={`g_button_wrap ${_activeStyleVariant}`} tag={"div"}>
          <Clickable
            clickableVisibility={
              applyPredicate(globalClickableLink)(linkIsSet) ||
              applyPredicate(globalClickableTypeButtonSubmitEtc)(isSet)
                ? true
                : false
            }
            customAriaLabel={globalClickableAriaLabel}
            customTargetUseBlankForANewWindow={
              globalClickableTargetUseBlankForANewWindow
            }
            customTypeButtonSubmitEtc={globalClickableTypeButtonSubmitEtc}
            id={id}
            link={globalClickableLink}
          />
          <Block className={`g_button_text ${_activeStyleVariant}`} tag={"div"}>
            {buttonText}
          </Block>
          {iconWrap}
        </Block>
      </DOM>
    </div>
  );
}
