/**
 * @generated
 * @file ButtonLearnMore (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { Clickable } from "../utils/Clickable";
import { IconArrowRight } from "../IconArrowRight";

/**
 * ButtonLearnMore
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ButtonLearnMore({
  linkLink = {
    href: "#",
  },

  linkTargetUseBlankForANewWindow = "",
  text = "Learn More",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"btn-text_wrap"}
        data-trigger={"hover focus"}
        tag={"div"}
      >
        <Block className={"btn-text"} tag={"div"}>
          {text}
        </Block>
        <Block className={"btn-text_icon_wrap icon-1x1-xxsmall"} tag={"div"}>
          <IconArrowRight />
        </Block>
        <Clickable
          customTargetUseBlankForANewWindow={linkTargetUseBlankForANewWindow}
          link={linkLink}
        />
      </Block>
    </div>
  );
}
