/**
 * @generated
 * @file AvatarsGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";

/**
 * AvatarsGroup
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function AvatarsGroup({
  image1 = "https://cdn.prod.website-files.com/69b36b5add91b49325a05878/6a0ce50a2cf7fa8d4a380040_detection-portrait-3.webp",
  image2 = "https://cdn.prod.website-files.com/69b36b5add91b49325a05878/6a0ce50b122203ca96fc9b6b_detection-portrait-2.webp",
  image3 = "https://cdn.prod.website-files.com/69b36b5add91b49325a05878/6a0ce50a9f680777c59c3a21_detection-portrait-1.webp",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"avatars_group"} tag={"div"}>
        <Block className={"avatar"} tag={"div"}>
          <Image
            alt={""}
            className={"avatar_img cover-absolute"}
            height={"auto"}
            loading={"lazy"}
            src={image1}
            width={"auto"}
          />
        </Block>
        <Block className={"avatar is-second"} tag={"div"}>
          <Image
            alt={""}
            className={"avatar_img cover-absolute"}
            height={"auto"}
            loading={"lazy"}
            src={image2}
            width={"auto"}
          />
        </Block>
        <Block className={"avatar is-third"} tag={"div"}>
          <Image
            alt={""}
            className={"avatar_img cover-absolute"}
            height={"auto"}
            loading={"lazy"}
            src={image3}
            width={"auto"}
          />
        </Block>
      </Block>
    </div>
  );
}
