/**
 * @generated
 * @file EyebrowItemWithIcon (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * EyebrowItemWithIcon
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function EyebrowItemWithIcon({
  eyebrowIconWrap,
  text = "Eyebrow Text",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"eyebrow_item_wrap"} tag={"div"}>
        {eyebrowIconWrap}
        <Block className={"eyebrow_text uppercase"} tag={"div"}>
          {text}
        </Block>
      </Block>
    </div>
  );
}
