/**
 * @generated
 * @file FormFormSelect (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { FormFormLabelText } from "../FormFormLabelText";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "../webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * FormFormSelect
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormSelect({
  allowMultiSelect = "",
  attributeName = "",
  attributeValue = "",
  autocomplete = "",
  classProp = "",
  inputMode = "text",
  labelClass = "",
  name = "Field Name",
  placeholder = "Placeholder Text",
  required = "",
  slot,
  tag = "span",
  text = "Form Label",
  type = "text",
  value = "Form Value",
  variant = "Base",
  visibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    "Label Hidden": "w-variant-a1bdb87c-cb17-9901-259a-5207fa5d626e",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM className={`form_label_wrap ${_activeStyleVariant}`} tag={"label"}>
          <FormFormLabelText
            labelClass={labelClass}
            labelVisibility={
              applyPredicate(variant)(styleVariantIsAny(["Label Hidden"]))
                ? false
                : true
            }
            tag={tag}
            text={text}
          />
          <DOM
            className={`form_select_wrap ${_activeStyleVariant}`}
            id={""}
            tag={"span"}
          >
            <DOM
              class={classProp}
              className={`form_field ${_activeStyleVariant}`}
              multiselect={allowMultiSelect}
              name={name}
              tag={"select"}
            >
              {slot}
            </DOM>
            <DOM
              aria-hidden={"true"}
              className={`form_select_icon ${_activeStyleVariant}`}
              fill={"none"}
              tag={"svg"}
              viewBox={"0 0 6 5"}
              width={"100%"}
            >
              <DOM
                d={"M0.5 1L3 3.5L5.5 1"}
                stroke={"currentColor"}
                stroke-width={"0.125rem"}
                tag={"path"}
                vector-effect={"non-scaling-stroke"}
              />
            </DOM>
          </DOM>
        </DOM>
      ) : null}
    </div>
  );
}
