/**
 * @generated
 * @file FormFormInput (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { FormFormLabelText } from "../FormFormLabelText";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "../webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * FormFormInput
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormInput({
  attributeName = "",
  attributeValue = "",
  autocomplete = "",
  classProp = "",
  inputMode = "text",
  labelClass = "",
  name = "Field Name",
  placeholder = "Placeholder Text",
  required = "",
  tag = "span",
  text = "Form Label",
  type = "text",
  value = "",
  variant = "Base",
  visibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    "Label Hidden": "w-variant-41686526-b347-23eb-d850-6b7acc3f3e66",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM className={`form_label_wrap ${_activeStyleVariant}`} tag={"label"}>
          <FormFormLabelText
            labelClass={labelClass}
            labelVisibility={
              applyPredicate(variant)(styleVariantIsAny(["Label Hidden"]))
                ? false
                : true
            }
            tag={tag}
            text={text}
          />
          <DOM
            autocomplete={autocomplete}
            class={classProp}
            className={`form_field ${_activeStyleVariant}`}
            inputmode={inputMode}
            name={name}
            placeholder={placeholder}
            required={required}
            tag={"input"}
            type={type}
            value={value}
          />
        </DOM>
      ) : null}
    </div>
  );
}
