/**
 * @generated
 * @file GridGuides (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * GridGuides
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function GridGuides({ visibility = true }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={"styleguide_guide_wrap"} tag={"div"}>
          <HtmlEmbed
            content={
              "<style>\nhtml:not(.wf-design-mode) .styleguide_guide_wrap {\n\tdisplay: none;\n}\n.styleguide_guide_layout {\n\tcounter-reset: gridguides;\n}\n.styleguide_guide_layout > div::before {\n  counter-increment: gridguides;\n  content: counter(gridguides);\n}\n</style>"
            }
          />
          <Block
            className={"styleguide_guide_contain container-large"}
            data-padding-bottom={"none"}
            data-padding-top={"none"}
            tag={"div"}
          >
            <Block
              className={"styleguide_guide_layout grid-custom"}
              tag={"div"}
            >
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
              <Block
                className={"styleguide_guide_column vflex-center-bottom"}
                tag={"div"}
              />
            </Block>
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
