/**
 * @generated
 * @file StarterJs (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * StarterJs
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function StarterJs({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <HtmlEmbed
        className={"embed-js"}
        content={
          '<script>\ndocument.addEventListener("DOMContentLoaded", function () {\n  document.querySelectorAll(".your-section").forEach((element) => {\n    if (element.dataset.scriptInitialized) return;\n    element.dataset.scriptInitialized = "true";\n    // run script here\n  });\n});\n</script>'
        }
      />
    </div>
  );
}
