/**
 * @generated
 * @file StrokePath (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * StrokePath
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function StrokePath({ path = "M18 24.8437L31 12.8438L18 0.843749" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"svg-path"} d={path} tag={"path"} />
    </div>
  );
}
