/**
 * @generated
 * @file TabsTabButton (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Text } from "../typography/Text";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "../webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * TabsTabButton
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function TabsTabButton({
  accordionText = "",
  attributeName = "",
  attributeValue = "",
  classProp = "is-active",
  iconWrap,
  text = "Tab 1",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    "Accordion Button": "w-variant-ed067e4a-6784-1be7-33d3-ab1b3d9297a3",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        class={classProp}
        className={`tabs_button_item ${_activeStyleVariant}`}
        data-tab={"button"}
        data-tab-item-id={""}
        data-trigger={""}
        id={""}
        role={"tab"}
        tag={"div"}
      >
        <Block
          className={`tabs_button_wrap ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Block
            className={`tabs_button_content_top ${_activeStyleVariant}`}
            tag={"div"}
          >
            {iconWrap}
            <DOM
              className={`tabs_button_text text-h6 ${_activeStyleVariant}`}
              tag={"span"}
            >
              {text}
            </DOM>
            <DOM
              className={`accordion-cms_toggle_icon ${_activeStyleVariant}`}
              data-tab={"icon"}
              tag={"span"}
            >
              <DOM
                aria-hidden={"true"}
                className={`accordion-cms_toggle_svg ${_activeStyleVariant}`}
                fill={"none"}
                tag={"svg"}
                viewBox={"0 0 66 64"}
                width={"100%"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <DOM
                  d={"M1 19L33 51L65 19"}
                  stroke={"currentColor"}
                  stroke-width={"0.09rem"}
                  tag={"path"}
                  vector-effect={"non-scaling-stroke"}
                />
              </DOM>
            </DOM>
          </Block>
          {applyPredicate(variant)(styleVariantIsAny(["Accordion Button"])) ? (
            <Block
              className={`tabs_button_content_wrap ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`tabs_button_content_mask ${_activeStyleVariant}`}
                data-tab={"button-accordion-mask"}
                tag={"div"}
              >
                <Block
                  className={`tabs_button_content_clip ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Text text={accordionText} />
                </Block>
              </Block>
            </Block>
          ) : null}
        </Block>
        <Block
          className={`tabs_button_line ${_activeStyleVariant}`}
          tag={"div"}
        />
      </DOM>
    </div>
  );
}
