/**
 * @generated
 * @file TabsTabContent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * TabsTabContent
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function TabsTabContent({ tabContentSlot, variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    "No Padding": "w-variant-c7d2f229-ad2a-4318-d718-b54e6e9cd9c0",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`tabs_content_item is-accordion ${_activeStyleVariant}`}
        data-tab={"panel"}
        // @ts-ignore - User-defined custom attribute(s)
        role={"tabpanel"}
        tag={"div"}
      >
        <Block
          className={`tabs_content_layout ${_activeStyleVariant}`}
          data-tab={"content"}
          tag={"div"}
        >
          {tabContentSlot}
        </Block>
      </Block>
    </div>
  );
}
