/**
 * @generated
 * @file Tag (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Tag
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Tag({
  classProp = "",
  customAttributeAttributeName = "",
  customAttributeAttributeValue = "",
  eyebrowIconWrap,
  tagText = "Tag title",
  tagVisibility = true,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    "No Icon": "w-variant-64abcbba-d779-d704-8d33-3f023f7aaf39",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {tagVisibility ? (
        <DOM
          class={classProp}
          className={`tag ${_activeStyleVariant}`}
          id={""}
          tag={"div"}
        >
          {eyebrowIconWrap}
          <Block
            className={`tag-text uppercase ${_activeStyleVariant}`}
            fs-list-field={"category"}
            tag={"div"}
          >
            {tagText}
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
