/**
 * @generated
 * @file IconL1Plus (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * IconL1Plus
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconL1Plus({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        fill={"none"}
        stroke-width={"1"}
        tag={"svg"}
        viewBox={"0 0 28 28"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <DOM
          d={
            "M14 3.5C19.775 3.5 24.5 8.225 24.5 14C24.5 19.775 19.775 24.5 14 24.5C8.225 24.5 3.5 19.775 3.5 14C3.5 8.225 8.225 3.5 14 3.5ZM14 1.75C7.2625 1.75 1.75 7.2625 1.75 14C1.75 20.7375 7.2625 26.25 14 26.25C20.7375 26.25 26.25 20.7375 26.25 14C26.25 7.2625 20.7375 1.75 14 1.75Z"
          }
          fill={"currentColor"}
          stroke-width={"1"}
          tag={"path"}
        />
        <DOM
          d={
            "M21 13.125H14.875V7H13.125V13.125H7V14.875H13.125V21H14.875V14.875H21V13.125Z"
          }
          fill={"currentColor"}
          stroke-width={"1"}
          tag={"path"}
        />
      </DOM>
    </div>
  );
}
