/**
 * @generated
 * @file IconsContainer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsNotAny } from "../webflow_modules/Basic/helpers/styleVariantIsNotAny";

/**
 * IconsContainer
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconsContainer({ variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    Plus: "w-variant-9a56dfa3-4576-7687-b933-ed30a1134beb",
    "Arrow Right": "w-variant-45443c47-5b75-7194-504f-e8fd997d2de3",
    "Arrow Left": "w-variant-f5cfaf21-5a78-7497-d9af-59ff1f6217f9",
    "Arrow Top": "w-variant-4b0cc625-48e4-057e-7c22-17f160bae3dd",
    "Arrow Bottom": "w-variant-447c0a22-014b-1b4c-79f9-3ab637baa768",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`icons-container ${_activeStyleVariant}`} tag={"div"}>
        {!applyPredicate(variant)(styleVariantIsNotAny(["Plus"])) ? (
          <DOM
            className={`svg ${_activeStyleVariant}`}
            fill={"none"}
            stroke-width={"1"}
            tag={"svg"}
            viewBox={"0 0 28 28"}
            width={"100%"}
            xmlns={"http://www.w3.org/2000/svg"}
          >
            <DOM
              d={
                "M14 3.5C19.775 3.5 24.5 8.225 24.5 14C24.5 19.775 19.775 24.5 14 24.5C8.225 24.5 3.5 19.775 3.5 14C3.5 8.225 8.225 3.5 14 3.5ZM14 1.75C7.2625 1.75 1.75 7.2625 1.75 14C1.75 20.7375 7.2625 26.25 14 26.25C20.7375 26.25 26.25 20.7375 26.25 14C26.25 7.2625 20.7375 1.75 14 1.75Z"
              }
              fill={"currentColor"}
              stroke-width={"1"}
              tag={"path"}
            />
            <DOM
              d={
                "M21 13.125H14.875V7H13.125V13.125H7V14.875H13.125V21H14.875V14.875H21V13.125Z"
              }
              fill={"currentColor"}
              stroke-width={"1"}
              tag={"path"}
            />
          </DOM>
        ) : null}
        {!applyPredicate(variant)(styleVariantIsNotAny(["Arrow Left"])) ? (
          <DOM
            className={`svg ${_activeStyleVariant}`}
            fill={"none"}
            tag={"svg"}
            viewBox={"0 0 16 16"}
            width={"100%"}
            xmlns={"http://www.w3.org/2000/svg"}
          >
            <DOM
              d={
                "M8.0026 12.6667L3.33594 8M3.33594 8L8.0026 3.33333M3.33594 8H12.6693"
              }
              stroke={"currentColor"}
              stroke-linecap={"round"}
              stroke-linejoin={"round"}
              tag={"path"}
            />
          </DOM>
        ) : null}
        {!applyPredicate(variant)(styleVariantIsNotAny(["Arrow Right"])) ? (
          <DOM
            className={`svg ${_activeStyleVariant}`}
            fill={"none"}
            tag={"svg"}
            viewBox={"0 0 16 16"}
            width={"100%"}
            xmlns={"http://www.w3.org/2000/svg"}
          >
            <DOM
              d={
                "M3.33594 8H12.6693M12.6693 8L8.0026 3.33333M12.6693 8L8.0026 12.6667"
              }
              stroke={"currentColor"}
              stroke-linecap={"round"}
              stroke-linejoin={"round"}
              tag={"path"}
            />
          </DOM>
        ) : null}
        {!applyPredicate(variant)(styleVariantIsNotAny(["Arrow Bottom"])) ? (
          <DOM
            className={`svg ${_activeStyleVariant}`}
            fill={"none"}
            tag={"svg"}
            viewBox={"0 0 16 16"}
            width={"100%"}
            xmlns={"http://www.w3.org/2000/svg"}
          >
            <DOM
              d={
                "M8.0026 3.33333V12.6667M8.0026 12.6667L12.6693 8M8.0026 12.6667L3.33594 8"
              }
              stroke={"currentColor"}
              stroke-linecap={"round"}
              stroke-linejoin={"round"}
              tag={"path"}
            />
          </DOM>
        ) : null}
        {!applyPredicate(variant)(styleVariantIsNotAny(["Arrow Top"])) ? (
          <DOM
            className={`svg ${_activeStyleVariant}`}
            fill={"none"}
            tag={"svg"}
            viewBox={"0 0 16 16"}
            width={"100%"}
            xmlns={"http://www.w3.org/2000/svg"}
          >
            <DOM
              d={
                "M3.33594 8L8.0026 3.33333M8.0026 3.33333L12.6693 8M8.0026 3.33333V12.6667"
              }
              stroke={"currentColor"}
              stroke-linecap={"round"}
              stroke-linejoin={"round"}
              tag={"path"}
            />
          </DOM>
        ) : null}
      </Block>
    </div>
  );
}
