/**
 * @generated
 * @file IconHexagon (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * IconHexagon
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconHexagon({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        fill={"none"}
        tag={"svg"}
        viewBox={"0 0 21 19"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <DOM
          d={
            "M4.09114 1.50306C4.63946 0.56646 5.6458 -0.0064722 6.73108 8.28471e-05L14.0052 0.0440178C15.0905 0.0505729 16.0898 0.635623 16.6268 1.57878L20.2258 7.90029C20.7627 8.84345 20.7557 10.0014 20.2074 10.938L16.5323 17.2156C15.984 18.1522 14.9776 18.7252 13.8924 18.7186L6.61825 18.6747C5.53296 18.6681 4.53361 18.0831 3.99665 17.1399L0.39767 10.8184C-0.139294 9.87523 -0.132296 8.71725 0.416025 7.78064L4.09114 1.50306Z"
          }
          fill={"currentColor"}
          tag={"path"}
        />
      </DOM>
    </div>
  );
}
