/**
 * @generated
 * @file Clickable (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { linkIsNotSet } from "../webflow_modules/Basic/helpers/linkIsNotSet";
import { linkIsSet } from "../webflow_modules/Basic/helpers/linkIsSet";

/**
 * Clickable
 *
 * Global link component
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Clickable({
  clickableVisibility = true,
  customAriaLabel = "",
  customTargetUseBlankForANewWindow = "",
  customTypeButtonSubmitEtc = "",
  id = "",

  link = {
    href: "#",
  },
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {clickableVisibility ? (
        <Block className={"g_clickable_wrap"} id={id} tag={"div"}>
          {applyPredicate(link)(linkIsSet) ? (
            <Link
              aria-label={customAriaLabel}
              block={"inline"}
              button={false}
              className={"g_clickable_link"}
              options={link}
              // @ts-ignore - User-defined custom attribute(s)
              target={customTargetUseBlankForANewWindow}
            />
          ) : null}
          {applyPredicate(link)(linkIsNotSet) ? (
            <DOM
              aria-label={customAriaLabel}
              className={"g_clickable_btn"}
              tag={"button"}
              type={customTypeButtonSubmitEtc}
            />
          ) : null}
        </Block>
      ) : null}
    </div>
  );
}
