/**
 * @generated
 * @file GlobalBackground (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * GlobalBackground
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function GlobalBackground({ classProp = "", variant = "Transparent" }) {
  const _styleVariantMap = {
    Transparent: "",
    "Background 1": "w-variant-3c5721ab-9a59-fe4b-c769-cea91b3d505f",
    "Background 2": "w-variant-9d323165-3469-4786-c485-c45ae564c4b4",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`g_background ${_activeStyleVariant}`} tag={"div"} />
    </div>
  );
}
