/**
 * @generated
 * @file Icon (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * Icon
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Icon({ classProp = "", iconContent, iconSize = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    XSmall: "w-variant-a9345e60-8d92-7837-575d-76a0bba2e87c",
    Small: "w-variant-fc4a9906-05f5-f9f1-0171-47bfa93af32f",
    Medium: "w-variant-bcbcef81-b776-a8fd-ac01-3cf731a17720",
    Large: "w-variant-5bb577b5-6279-a8ea-0b89-907495ffdc53",
    XLarge: "w-variant-c461513f-c0e9-4722-14c7-02f11adb6cc4",
  };

  const _activeStyleVariant = _styleVariantMap[iconSize];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`g_icon_wrap ${_activeStyleVariant}`} tag={"div"}>
        {iconContent}
      </Block>
    </div>
  );
}
