/**
 * @generated
 * @file Image (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Image2 from "../webflow_modules/Basic/components/Image";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Image
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Image({
  aspectRatioCustom = "",
  image = "",
  imageAltText = "__wf_reserved_inherit",
  imageClass = "",
  maxWidth = -1,
  objectPosition = "object-position: 50% 50%;",
  variant = "Base",
  visibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    "Wide 16/9": "w-variant-1bbec642-3524-7a3e-f039-cd8758e7f341",
    "Wide 3/2": "w-variant-6cd38105-2660-5ffa-38ee-5c020b593600",
    "Wide 5/4": "w-variant-83576c14-0186-0114-fbec-d98eec69c142",
    "Sqiare 1/1": "w-variant-4e43f3ce-c409-fa12-78b0-74e5e7ec5bf1",
    "Portrait 4/5": "w-variant-64973f4d-448e-de59-a2a5-83e916b292f3",
    "Portrait 2/3": "w-variant-d464e4d1-b6e8-0b76-50f8-5b2366e0eb5b",
    Cover: "w-variant-ae154d96-c491-2ceb-1b80-475208f0e9ec",
    Auto: "w-variant-b2e0c6f1-56b3-317e-cac5-86931a6fbb38",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM
          class={imageClass}
          className={`image-wrapper position-relative ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          style={aspectRatioCustom}
          tag={"div"}
        >
          <Image2
            className={`image cover-absolute ${_activeStyleVariant}`}
            height={"auto"}
            loading={"lazy"}
            src={image}
            width={"auto"}
          />
        </DOM>
      ) : null}
    </div>
  );
}
