/**
 * @generated
 * @file ModalButtonClose (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * ModalButtonClose
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ModalButtonClose({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        autofocus={" "}
        className={"modal-new_close"}
        data-modal-new-close={" "}
        tag={"button"}
      >
        <DOM
          className={"modal-new_close-icon"}
          fill={"none"}
          tag={"svg"}
          viewBox={"0 0 28 28"}
          width={"100%"}
          xmlns={"http://www.w3.org/2000/svg"}
        >
          <DOM
            d={
              "M15.2372 14L22.75 6.48725L21.5128 5.25L14 12.7628L6.48725 5.25L5.25 6.48725L12.7628 14L5.25 21.5128L6.48725 22.75L14 15.2372L21.5128 22.75L22.75 21.5128L15.2372 14Z"
            }
            fill={"currentColor"}
            tag={"path"}
          />
        </DOM>
      </DOM>
    </div>
  );
}
