/**
 * @generated
 * @file BackgroundLines (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * BackgroundLines
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function BackgroundLines({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"background_grid container-large"} tag={"div"} />
    </div>
  );
}
