/**
 * @generated
 * @file ButtonButtonArrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { Clickable } from "./utils/Clickable";
import { IconArrowRight } from "./IconArrowRight";

/**
 * ButtonButtonArrow
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ButtonButtonArrow({
  attributeName = "",
  attributeValue = "",
  butonArrow = "Left",
  classProp = "",
  clickableCustomAriaLabel = "",

  clickableLink = {
    href: "#",
  },

  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM
          class={classProp}
          className={"button_arrow_wrap"}
          data-button={""}
          data-trigger={"hover focus"}
          id={""}
          tag={"div"}
        >
          <Block className={"button_arrow_element"} tag={"div"}>
            <Block className={"button_arrow_icon"} tag={"div"}>
              <IconArrowRight variant={butonArrow} />
            </Block>
          </Block>
          <Clickable
            customAriaLabel={clickableCustomAriaLabel}
            customTypeButtonSubmitEtc={"button"}
            link={clickableLink}
          />
        </DOM>
      ) : null}
    </div>
  );
}
