/**
 * @generated
 * @file DitherSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { applyPredicate } from "./webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "./webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * DitherSection
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function DitherSection({
  animate = false,
  classProp = "",
  ditherColor = "#3066D9",
  variant = "Up",
}) {
  const _styleVariantMap = {
    Up: "",
    Down: "w-variant-a66fe453-47d3-e45f-0d60-04fec08fc854",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        class={classProp}
        className={`dither-section ${_activeStyleVariant}`}
        data-dither-animate={animate ? "true" : "false"}
        data-dither-color={ditherColor}
        data-dither-direction={
          applyPredicate(variant)(styleVariantIsAny(["Down"])) ? "down" : "up"
        }
        data-dither-seed={"7"}
        tag={"canvas"}
      />
    </div>
  );
}
