/**
 * @generated
 * @file ElementsAccordionItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DOM from "./webflow_modules/Builtin/components/DOM";
import RichText from "./webflow_modules/Basic/components/RichText";
import { IconIconArrow } from "./IconIconArrow";

/**
 * ElementsAccordionItem
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ElementsAccordionItem({
  content = "",
  text = "This is some text inside of a div block.",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"accordion_item"}
        data-state={""}
        // @ts-ignore - User-defined custom attribute(s)
        role={"listitem"}
        tag={"div"}
      >
        <Block className={"accordion_component"} tag={"div"}>
          <DOM className={"accordion_toggle_heading"} tag={"h3"}>
            <DOM
              aria-expanded={"false"}
              className={"accordion_toggle_button"}
              tag={"button"}
            >
              <DOM className={"accordion_toggle_text text-h5"} tag={"span"}>
                {text}
              </DOM>
              <DOM className={"accordion_toggle_icon"} tag={"span"}>
                <IconIconArrow variant={"Bottom"} />
              </DOM>
            </DOM>
          </DOM>
          <Block className={"accordion_content_wrap"} tag={"div"}>
            <Block className={"accordion_content_padding"} tag={"div"}>
              <RichText
                className={"accordion_content_text text-rich-text"}
                tag={"div"}
              >
                {content}
              </RichText>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
