/**
 * @generated
 * @file Eyebrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Eyebrow
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Eyebrow({
  classProp = "",
  icon,
  secondItem,
  text = "This is some text inside of a div block.",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    "Color Background": "w-variant-24af161c-0ffe-e608-7929-46319b66c3a3",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`eyebrow ${_activeStyleVariant}`} tag={"div"}>
        <Block className={`eyebrow_content ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`eyebrow_item_wrap ${_activeStyleVariant}`}
            tag={"div"}
          >
            {icon}
            <Block
              className={`eyebrow_text uppercase ${_activeStyleVariant}`}
              tag={"div"}
            >
              {text}
            </Block>
          </Block>
          {secondItem}
        </Block>
      </Block>
    </div>
  );
}
