/**
 * @generated
 * @file FormFormLabelText (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * FormFormLabelText
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormLabelText({
  labelClass = "",
  labelVisibility = true,
  tag = "span",
  text = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {labelVisibility ? (
        <DOM class={labelClass} className={"form_label_text"} tag={tag}>
          {text}
        </DOM>
      ) : null}
    </div>
  );
}
