/**
 * @generated
 * @file FormCheckUi (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * FormCheckUi
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormCheckUi({
  attributeName = "",
  attributeValue = "",
  checked = "",
  labelAttributeName = "",
  labelAtttributeValue = "",
  name = "Name",
  required = "",
  type = "checkbox",
  value = "Value",
  variant = "Checkbox",
}) {
  const _styleVariantMap = {
    Checkbox: "",
    Radio: "w-variant-9fc24ace-5d5c-4d65-a438-7af771308f06",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        className={`form_ui_label ${_activeStyleVariant}`}
        data-state={"checked"}
        role={"listitem"}
        tag={"label"}
      >
        <DOM
          checked={checked}
          className={`form_ui_input ${_activeStyleVariant}`}
          name={name}
          required={required}
          tag={"input"}
          type={type}
          value={value}
        />
        <DOM
          className={`form_ui_visual_wrap ${_activeStyleVariant}`}
          tag={"span"}
        >
          <DOM
            className={`form_ui_visual_inner ${_activeStyleVariant}`}
            tag={"span"}
          >
            <DOM
              aria-hidden={"true"}
              className={`form_ui_visual_icon ${_activeStyleVariant}`}
              fill={"none"}
              tag={"svg"}
              viewBox={"0 0 11 8"}
            >
              <DOM
                d={"M1 4L4 7L10 1"}
                stroke={"currentColor"}
                stroke-width={"0.125rem"}
                tag={"path"}
                vector-effect={"non-scaling-stroke"}
              />
            </DOM>
          </DOM>
        </DOM>
        <DOM className={`form_ui_text ${_activeStyleVariant}`} tag={"span"}>
          {"I agree to the terms"}
        </DOM>
      </DOM>
    </div>
  );
}
