/**
 * @generated
 * @file FormFormDate (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { FormFormLabelText } from "./FormFormLabelText";

/**
 * FormFormDate
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormDate({
  autocomplete = "",
  classProp = "",
  formFormLabelTextLabelClass = "",
  formFormLabelTextLabelVisibility = true,
  formFormLabelTextTag = "span",
  formFormLabelTextText = "",
  inputMode = "text",
  placeholder = "Placeholder",
  required = "",
  text = "Completion Date",
  value = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"form_label_wrap"} data-trigger={"focus"} tag={"label"}>
        <FormFormLabelText
          labelClass={formFormLabelTextLabelClass}
          labelVisibility={formFormLabelTextLabelVisibility}
          tag={formFormLabelTextTag}
          text={formFormLabelTextText}
        />
        <DOM
          autocomplete={autocomplete}
          class={classProp}
          className={"form_field"}
          inputmode={inputMode}
          name={"Completion Date"}
          placeholder={placeholder}
          required={required}
          tag={"input"}
          type={"date"}
          value={value}
        />
      </DOM>
    </div>
  );
}
