/**
 * @generated
 * @file FormFormCheckbox (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { FormCheckUi } from "./FormCheckUi";

/**
 * FormFormCheckbox
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormCheckbox({
  classProp = "",
  formCheckUiAttributeName = "",
  formCheckUiAttributeValue = "",
  formCheckUiChecked = "",
  formCheckUiLabelAttributeName = "",
  formCheckUiLabelAtttributeValue = "",
  formCheckUiName = "Name",
  formCheckUiRequired = "",
  formCheckUiType = "checkbox",
  formCheckUiValue = "Value",
  formCheckUiVariant = "Checkbox",
  role = "none",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        class={classProp}
        className={"form_ui_item"}
        data-state={"checked"}
        role={role}
        tag={"div"}
      >
        <FormCheckUi
          attributeName={formCheckUiAttributeName}
          attributeValue={formCheckUiAttributeValue}
          checked={formCheckUiChecked}
          labelAttributeName={formCheckUiLabelAttributeName}
          labelAtttributeValue={formCheckUiLabelAtttributeValue}
          name={formCheckUiName}
          required={formCheckUiRequired}
          type={"checkbox"}
          value={"Value"}
          variant={formCheckUiVariant}
        />
      </DOM>
    </div>
  );
}
