/**
 * @generated
 * @file FormFormOption (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * FormFormOption
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FormFormOption({
  hidden = "",
  selected = "",
  text = "Option 1",
  value = "Option 1",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM hidden={hidden} selected={selected} tag={"option"} valiue={value}>
        {text}
      </DOM>
    </div>
  );
}
