/**
 * @generated
 * @file IconAgent68 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * IconAgent68
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconAgent68({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        fill={"none"}
        tag={"svg"}
        viewBox={"0 0 980 526"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <DOM clip-path={"url(#clip0_3563_398)"} tag={"g"}>
          <DOM fill={"white"} id={"path-1-inside-1_3563_398"} tag={"mask"}>
            <DOM
              d={
                "M980.19 532.239C980.19 398.935 928.555 271.09 836.645 176.83C744.734 82.5693 620.077 29.6143 490.095 29.6143C360.114 29.6142 235.456 82.5692 143.546 176.83C51.6349 271.09 1.96266e-05 398.935 0 532.239L490.095 532.239H980.19Z"
              }
              tag={"path"}
            />
          </DOM>
          <DOM
            d={
              "M980.19 532.239C980.19 398.935 928.555 271.09 836.645 176.83C744.734 82.5693 620.077 29.6143 490.095 29.6143C360.114 29.6142 235.456 82.5692 143.546 176.83C51.6349 271.09 1.96266e-05 398.935 0 532.239L490.095 532.239H980.19Z"
            }
            mask={"url(#path-1-inside-1_3563_398)"}
            stroke={"url(#paint0_linear_3563_398)"}
            stroke-width={"1.90366"}
            tag={"path"}
          />
          <DOM fill={"white"} id={"path-2-inside-2_3563_398"} tag={"mask"}>
            <DOM
              d={
                "M852.049 532.239C852.049 398.935 813.915 271.09 746.035 176.83C678.156 82.5693 586.091 29.6143 490.095 29.6143C394.099 29.6142 302.035 82.5692 234.155 176.83C166.275 271.09 128.141 398.935 128.141 532.239L490.095 532.239H852.049Z"
              }
              tag={"path"}
            />
          </DOM>
          <DOM
            d={
              "M852.049 532.239C852.049 398.935 813.915 271.09 746.035 176.83C678.156 82.5693 586.091 29.6143 490.095 29.6143C394.099 29.6142 302.035 82.5692 234.155 176.83C166.275 271.09 128.141 398.935 128.141 532.239L490.095 532.239H852.049Z"
            }
            mask={"url(#path-2-inside-2_3563_398)"}
            stroke={"url(#paint1_linear_3563_398)"}
            stroke-width={"1.90366"}
            tag={"path"}
          />
          <DOM fill={"white"} id={"path-3-inside-3_3563_398"} tag={"mask"}>
            <DOM
              d={
                "M721.814 532.239C721.814 398.935 697.401 271.09 653.945 176.83C610.489 82.5693 551.551 29.6143 490.095 29.6143C428.639 29.6142 369.701 82.5692 326.245 176.83C282.789 271.09 258.376 398.935 258.376 532.239L490.095 532.239H721.814Z"
              }
              tag={"path"}
            />
          </DOM>
          <DOM
            d={
              "M721.814 532.239C721.814 398.935 697.401 271.09 653.945 176.83C610.489 82.5693 551.551 29.6143 490.095 29.6143C428.639 29.6142 369.701 82.5692 326.245 176.83C282.789 271.09 258.376 398.935 258.376 532.239L490.095 532.239H721.814Z"
            }
            mask={"url(#path-3-inside-3_3563_398)"}
            stroke={"url(#paint2_linear_3563_398)"}
            stroke-width={"1.90366"}
            tag={"path"}
          />
          <DOM fill={"white"} id={"path-4-inside-4_3563_398"} tag={"mask"}>
            <DOM
              d={
                "M555.735 532.239C555.735 398.935 548.82 271.09 536.51 176.83C524.2 82.5693 507.504 29.6143 490.095 29.6143C472.687 29.6142 455.991 82.5692 443.681 176.83C431.371 271.09 424.456 398.935 424.456 532.239L490.095 532.239H555.735Z"
              }
              tag={"path"}
            />
          </DOM>
          <DOM
            d={
              "M555.735 532.239C555.735 398.935 548.82 271.09 536.51 176.83C524.2 82.5693 507.504 29.6143 490.095 29.6143C472.687 29.6142 455.991 82.5692 443.681 176.83C431.371 271.09 424.456 398.935 424.456 532.239L490.095 532.239H555.735Z"
            }
            mask={"url(#path-4-inside-4_3563_398)"}
            stroke={"url(#paint3_linear_3563_398)"}
            stroke-width={"1.90366"}
            tag={"path"}
          />
        </DOM>
        <DOM tag={"defs"}>
          <DOM
            gradientUnits={"userSpaceOnUse"}
            id={"paint0_linear_3563_398"}
            tag={"lineargradient"}
            x1={"490.095"}
            x2={"490.095"}
            y1={"29.6143"}
            y2={"194.863"}
          >
            <DOM stop-color={"#FDB306"} tag={"stop"} />
            <DOM offset={"1"} stop-color={"#DBD9CB"} tag={"stop"} />
          </DOM>
          <DOM
            gradientUnits={"userSpaceOnUse"}
            id={"paint1_linear_3563_398"}
            tag={"lineargradient"}
            x1={"490.095"}
            x2={"490.095"}
            y1={"29.6143"}
            y2={"181.252"}
          >
            <DOM stop-color={"#FDB306"} tag={"stop"} />
            <DOM offset={"1"} stop-color={"#DBD9CB"} tag={"stop"} />
          </DOM>
          <DOM
            gradientUnits={"userSpaceOnUse"}
            id={"paint2_linear_3563_398"}
            tag={"lineargradient"}
            x1={"490.095"}
            x2={"490.095"}
            y1={"29.6143"}
            y2={"199.766"}
          >
            <DOM stop-color={"#FDB306"} tag={"stop"} />
            <DOM offset={"1"} stop-color={"#DBD9CB"} tag={"stop"} />
          </DOM>
          <DOM
            gradientUnits={"userSpaceOnUse"}
            id={"paint3_linear_3563_398"}
            tag={"lineargradient"}
            x1={"490.095"}
            x2={"490.095"}
            y1={"29.6143"}
            y2={"532.239"}
          >
            <DOM stop-color={"#FDB306"} tag={"stop"} />
            <DOM offset={"0.25"} stop-color={"#DBD9CB"} tag={"stop"} />
          </DOM>
          <DOM id={"clip0_3563_398"} tag={"clippath"}>
            <DOM fill={"white"} height={"526"} tag={"rect"} width={"980"} />
          </DOM>
        </DOM>
      </DOM>
    </div>
  );
}
