/**
 * @generated
 * @file IconHeart (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * IconHeart
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconHeart({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        fill={"none"}
        tag={"svg"}
        viewBox={"0 0 25 25"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <DOM
          d={
            "M16.7617 3.01331C14.8172 3.01331 13.1147 3.8495 12.0534 5.26293C10.9922 3.8495 9.28964 3.01331 7.34512 3.01331C5.79724 3.01505 4.31327 3.63071 3.21876 4.72523C2.12424 5.81974 1.50858 7.30371 1.50684 8.85159C1.50684 15.4432 11.2803 20.7786 11.6965 20.999C11.8062 21.058 11.9288 21.0889 12.0534 21.0889C12.178 21.0889 12.3006 21.058 12.4103 20.999C12.8265 20.7786 22.6 15.4432 22.6 8.85159C22.5982 7.30371 21.9826 5.81974 20.8881 4.72523C19.7935 3.63071 18.3096 3.01505 16.7617 3.01331ZM12.0534 19.4735C10.3339 18.4716 3.01349 13.9073 3.01349 8.85159C3.01498 7.70323 3.47183 6.60233 4.28384 5.79031C5.09586 4.9783 6.19676 4.52145 7.34512 4.51996C9.17664 4.51996 10.7144 5.49552 11.3566 7.06244C11.4133 7.2006 11.5099 7.31878 11.634 7.40195C11.758 7.48512 11.904 7.52952 12.0534 7.52952C12.2028 7.52952 12.3488 7.48512 12.4729 7.40195C12.5969 7.31878 12.6935 7.2006 12.7502 7.06244C13.3924 5.49269 14.9302 4.51996 16.7617 4.51996C17.9101 4.52145 19.011 4.9783 19.823 5.79031C20.635 6.60233 21.0918 7.70323 21.0933 8.85159C21.0933 13.8998 13.771 18.4706 12.0534 19.4735Z"
          }
          fill={"currentColor"}
          tag={"path"}
        />
      </DOM>
    </div>
  );
}
