/**
 * @generated
 * @file IconArrowRight (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { StrokePath } from "./miscellaneous/StrokePath";

/**
 * IconArrowRight
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconArrowRight({ variant = "Right" }) {
  const _styleVariantMap = {
    Right: "",
    Left: "w-variant-4a094eb7-c9a7-7407-d976-4a1c02e5fbff",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        className={`svg ${_activeStyleVariant}`}
        fill={"none"}
        stroke-width={"1"}
        tag={"svg"}
        viewBox={"0 0 33 26"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <StrokePath />
        <StrokePath path={"M30.5 13L0 13"} />
      </DOM>
    </div>
  );
}
