/**
 * @generated
 * @file IconChart (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * IconChart
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconChart({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        fill={"none"}
        tag={"svg"}
        viewBox={"0 0 60 60"}
        width={"100%"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <DOM
          d={
            "M55.6313 12.9807V27.8157C55.6313 28.3075 55.4359 28.7791 55.0882 29.1269C54.7404 29.4747 54.2687 29.67 53.7769 29.67C53.2851 29.67 52.8135 29.4747 52.4657 29.1269C52.1179 28.7791 51.9226 28.3075 51.9226 27.8157V17.4567L32.8364 36.5451C32.6642 36.7176 32.4597 36.8543 32.2345 36.9476C32.0094 37.041 31.7681 37.089 31.5244 37.089C31.2807 37.089 31.0394 37.041 30.8143 36.9476C30.5892 36.8543 30.3847 36.7176 30.2125 36.5451L22.2526 28.5829L6.87514 43.9626C6.52718 44.3106 6.05525 44.5061 5.56317 44.5061C5.07109 44.5061 4.59916 44.3106 4.2512 43.9626C3.90324 43.6147 3.70776 43.1428 3.70776 42.6507C3.70776 42.1586 3.90324 41.6867 4.2512 41.3387L20.9406 24.6493C21.1128 24.4769 21.3173 24.3401 21.5424 24.2468C21.7676 24.1535 22.0089 24.1055 22.2526 24.1055C22.4962 24.1055 22.7375 24.1535 22.9627 24.2468C23.1878 24.3401 23.3923 24.4769 23.5645 24.6493L31.5244 32.6115L49.3009 14.835H38.9419C38.4501 14.835 37.9785 14.6397 37.6307 14.2919C37.2829 13.9441 37.0876 13.4725 37.0876 12.9807C37.0876 12.4888 37.2829 12.0172 37.6307 11.6694C37.9785 11.3217 38.4501 11.1263 38.9419 11.1263H53.7769C54.2687 11.1263 54.7404 11.3217 55.0882 11.6694C55.4359 12.0172 55.6313 12.4888 55.6313 12.9807Z"
          }
          fill={"currentColor"}
          tag={"path"}
        />
      </DOM>
    </div>
  );
}
