/**
 * @generated
 * @file IconHexagonBase (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * IconHexagonBase
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconHexagonBase({ classProp = "", slot, variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    Light: "w-variant-0f657791-f355-cf6a-820a-315988ef23f2",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`icon_hexagon ${_activeStyleVariant}`} tag={"div"}>
        <Block
          className={`icon_wrap icon-1x1-xsmall ${_activeStyleVariant}`}
          tag={"div"}
        >
          {slot}
        </Block>
      </Block>
    </div>
  );
}
