/**
 * @generated
 * @file IconIconArrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";
import { StrokePath } from "./miscellaneous/StrokePath";

/**
 * IconIconArrow
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function IconIconArrow({ variant = "Right" }) {
  const _styleVariantMap = {
    Right: "",
    Left: "w-variant-da5de2ad-8379-2d0e-f128-fcd0dbde9ccd",
    Top: "w-variant-559ed636-1306-91ce-62d6-6dcde6cfe508",
    Bottom: "w-variant-8f6fb4d1-d5ef-5310-3624-f8e64665288d",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        aria-hidden={"true"}
        className={`svg ${_activeStyleVariant}`}
        fill={"none"}
        height={"100%"}
        tag={"svg"}
        viewBox={"0 0 66 70"}
        width={"100%"}
      >
        <StrokePath path={"M17 2L50 34.9999L17 68"} />
      </DOM>
    </div>
  );
}
