/**
 * @generated
 * @file ImageMask (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * ImageMask
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ImageMask({
  backgroundColor = "",
  gridCell = "5",
  gridGap = "3",
  gridSeed = "240",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"pixel-grid-overlay"}
        data-grid-bg={backgroundColor}
        data-grid-cell={gridCell}
        data-grid-gap={gridGap}
        data-grid-seed={gridSeed}
        tag={"div"}
      />
    </div>
  );
}
