/**
 * @generated
 * @file TextPlain (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import DOM from "./webflow_modules/Builtin/components/DOM";

/**
 * TextPlain
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function TextPlain({
  attributes = {},
  classProp = "",
  maxWidth = -1,
  style = "",
  tag = "p",
  text = "Lorem ipsum ",
  variant = "Text Regular",
}) {
  const _styleVariantMap = {
    "Text Regular": "",
    "Text Tiny": "w-variant-0e6b7d9d-b309-4ae1-5b5f-be33b1705b60",
    "Text Small": "w-variant-35803fae-f10d-adf8-3729-1b6b12969064",
    "Text Large": "w-variant-26b640cd-796f-a315-fa06-55fe454e1f96",
    H6: "w-variant-eec687b2-d2f4-e9f9-3517-d72685f7653f",
    H5: "w-variant-1886d521-4632-4301-2695-0548ce47632c",
    H4: "w-variant-d44b6e38-6ded-576a-727b-386aef5c0fa2",
    H3: "w-variant-271013c1-ea70-e04a-fdd3-be41fcb5b15a",
    H2: "w-variant-6984480e-130a-80bd-5800-640148601b41",
    H1: "w-variant-80d1b53a-6a64-42af-0b17-d3c424388cc2",
    Display: "w-variant-74464156-7a75-1f5c-816e-a5d494dcec9a",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={`text ${_activeStyleVariant}`} tag={tag}>
        <DOM tag={"span"}>{text}</DOM>
      </DOM>
    </div>
  );
}
