/**
 * @generated
 * @file ContentSpacer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * ContentSpacer
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ContentSpacer({ variant = "1" }) {
  const _styleVariantMap = {
    1: "",
    2: "w-variant-5a13aa08-1d6e-b2d4-55cb-e92d3ff7f13e",
    3: "w-variant-f0992250-3701-4921-b341-9ec6fa65e555",
    4: "w-variant-86766616-a30b-a470-f71f-5d2afbec017c",
    5: "w-variant-02f8d0db-b8f8-d1e5-91ea-a4f4f7192b66",
    6: "w-variant-43c304d2-106f-a8b1-fe0d-d81a4b046d58",
    7: "w-variant-64fb5cb8-7650-ac5a-43ff-cad0a33d7a1d",
    8: "w-variant-eecc3bac-72ad-0f57-32f1-49bf06a0082c",
    none: "w-variant-c998fcbe-670a-1258-9257-6e4fd0522e21",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`content-spacer ${_activeStyleVariant}`} tag={"div"} />
    </div>
  );
}
