/**
 * @generated
 * @file ContentWrap (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ContentSpacer } from "./ContentSpacer";

/**
 * ContentWrap
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function ContentWrap({
  align = "Left",
  classProp = "align-self-center margin-trim",
  content,
  contentWrapperClass = "",
  spacingPaddingBottom = "1",
  spacingPaddingTop = "1",
}) {
  const _styleVariantMap = {
    Left: "",
    Center: "w-variant-d8340dc9-4260-c57e-0e76-99ef8f2387b4",
    Right: "w-variant-193ecd79-81f4-eabe-ea59-f41c971eba1c",
    "Center Mobile": "w-variant-fb71a62a-953a-adf4-6474-f0238b959a27",
  };

  const _activeStyleVariant = _styleVariantMap[align];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`content_wrapper ${_activeStyleVariant}`} tag={"div"}>
        <ContentSpacer variant={spacingPaddingTop} />
        {content}
        <ContentSpacer variant={spacingPaddingBottom} />
      </Block>
    </div>
  );
}
