/**
 * @generated
 * @file FooterFooterLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * FooterFooterLink
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FooterFooterLink({
  link = {
    href: "#",
  },

  text = "Link Text",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"footer_group_item"} role={"listitem"} tag={"div"}>
        <Link
          block={"inline"}
          button={false}
          className={"footer_link_wrap p-block-2"}
          options={link}
        >
          <Block className={"footer_link_text"} tag={"div"}>
            {text}
          </Block>
        </Link>
      </DOM>
    </div>
  );
}
