/**
 * @generated
 * @file FooterLinksColumn (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";

/**
 * FooterLinksColumn
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function FooterLinksColumn({ footerGroupList, title = "Heading Text" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"footer_group_wrap"} tag={"div"}>
        <Heading
          className={"footer_group_title mb-2 text-weight-bold text-h3"}
          tag={"h3"}
        >
          {title}
        </Heading>
        {footerGroupList}
      </Block>
    </div>
  );
}
