/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Emphasized from "../webflow_modules/Basic/components/Emphasized";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { BackgroundLines } from "../BackgroundLines";
import { ContentSpacer } from "./ContentSpacer";
import { FooterFooterLink } from "./FooterFooterLink";
import { FooterLinksColumn } from "./FooterLinksColumn";
import { Header } from "../typography/Header";
import { Logo } from "../svg/Logo";
import { SectionSpace } from "./SectionSpace";

/**
 * Footer
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Footer({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer_wrap theme-dark"}
        grid={{
          type: "section",
        }}
        tag={"footer"}
      >
        <Block className={"footer_contain container-large"} tag={"div"}>
          <SectionSpace variant={"Small"} />
          <Block className={"footer_layout grid-above px-content"} tag={"div"}>
            <Block className={"footer_content column-7"} tag={"div"}>
              <Header
                customClass={"mb-4 highlight is-yellow"}
                size={"H2"}
                text={
                  <Paragraph>
                    {"Community Inspired."}
                    <br />
                    <Emphasized>
                      {"AI Enhanced."}
                      <br />
                      {"Better Detections."}
                    </Emphasized>
                  </Paragraph>
                }
              />
              <Link
                block={"inline"}
                button={false}
                className={"footer_logo_wrap"}
                options={{
                  href: "#",
                }}
              >
                <Logo style={{ "maxWidth": "14rem" }} />
              </Link>
              <Block className={"footer_social_wrap"} tag={"div"}>
                <Paragraph className={"footer_social_title"}>
                  {"Follow Us"}
                </Paragraph>
                <DOM
                  className={"footer_social_list mt-2"}
                  role={"list"}
                  tag={"div"}
                >
                  <DOM
                    className={"footer_social_item"}
                    role={"listitem"}
                    tag={"div"}
                  >
                    <Link
                      block={"inline"}
                      button={false}
                      className={"sm-link icon-1x1-xsmall"}
                      options={{
                        href: "https://www.linkedin.com/company/detectionsai/",
                        target: "_blank",
                      }}
                    >
                      <DOM
                        fill={"none"}
                        stroke-width={"1"}
                        tag={"svg"}
                        viewBox={"0 0 28 28"}
                        width={"100%"}
                        xmlns={"http://www.w3.org/2000/svg"}
                      >
                        <DOM
                          d={
                            "M22.925 3.5H5.075C4.2 3.5 3.5 4.2 3.5 4.9875V22.925C3.5 23.7125 4.2 24.4125 5.075 24.4125H22.925C23.8 24.4125 24.5 23.7125 24.5 22.925V4.9875C24.5 4.2 23.8 3.5 22.925 3.5ZM9.7125 21.35H6.65V11.375H9.7125V21.35ZM8.225 9.975C7.2625 9.975 6.3875 9.1875 6.3875 8.1375C6.3875 7.0875 7.175 6.3 8.225 6.3C9.1875 6.3 10.0625 7.0875 10.0625 8.1375C10.0625 9.1875 9.1875 9.975 8.225 9.975ZM21.4375 21.2625H18.375V16.3625C18.375 15.225 18.375 13.65 16.7125 13.65C15.05 13.65 14.875 14.9625 14.875 16.1875V21.175H11.8125V11.375H14.7V12.6875H14.7875C15.225 11.9 16.275 11.025 17.7625 11.025C20.9125 11.025 21.525 13.125 21.525 15.8375V21.2625H21.4375Z"
                          }
                          fill={"currentColor"}
                          stroke-width={"1"}
                          tag={"path"}
                        />
                      </DOM>
                    </Link>
                  </DOM>
                </DOM>
              </Block>
            </Block>
            <Block className={"footer_nav"} tag={"nav"}>
              <Block className={"footer_col"} tag={"div"}>
                <FooterLinksColumn
                  footerGroupList={
                    <>
                      <FooterFooterLink
                        link={{
                          href: "/about",
                        }}
                        text={"About"}
                      />
                      <FooterFooterLink
                        link={{
                          href: "/resources",
                        }}
                        text={"Resources"}
                      />
                      <FooterFooterLink
                        link={{
                          href: "/leaderboard",
                        }}
                        text={"Leaderboard"}
                      />
                    </>
                  }
                  title={"Company"}
                />
              </Block>
            </Block>
          </Block>
        </Block>
        <ContentSpacer variant={"8"} />
        <Block className={"footer_bottom p-block-4"} tag={"div"}>
          <Block
            className={"footer_bottom_contain container-large"}
            tag={"div"}
          >
            <Block className={"footer_bottom_layout"} tag={"div"}>
              <DOM className={"footer_bottom_text text-size-small"} tag={"div"}>
                <DOM tag={"span"}>{"© "}</DOM>
                <DOM data-dynamic-year={""} tag={"span"}>
                  {"{{year}}"}
                </DOM>
                <DOM tag={"span"}>{"Copyright. All Rights Reserved."}</DOM>
              </DOM>
              <NotSupported _atom={"Collection List"} />
            </Block>
          </Block>
          <HtmlEmbed
            className={"embed-js"}
            content={
              '<script>\ndocument.addEventListener("DOMContentLoaded", function () {\n  document.querySelectorAll("[data-dynamic-year]").forEach(function (el) {\n    el.textContent = new Date().getFullYear();\n  });\n});\n</script>'
            }
          />
        </Block>
        <SectionSpace variant={"None"} />
        <BackgroundLines />
      </Section>
    </div>
  );
}
