/**
 * @generated
 * @file Grid (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Grid
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Grid({
  classProp = "",
  content,
  largeScreen = 2,
  mediumScreen = 1,
  minimumColumnSize = 14,
  role = "",
  smallScreen = 0,
  style = "",
  variant = "Base",
  visibility = true,
  xSmallScreen = 0,
}) {
  const _styleVariantMap = {
    Base: "",
    "Self Contained": "w-variant-431f3b83-eb2b-24f4-ca8c-e44e6feb672f",
    Autofit: "w-variant-5ce4e529-81ac-369b-bfa9-c1103efd1d59",
    Autofill: "w-variant-5808bfc6-4ed8-ae4c-1411-0f9babb9b5cb",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        class={classProp}
        className={`grid-wrapper ${_activeStyleVariant}`}
        data-number={formatNumber(-1)(minimumColumnSize)}
        style={style}
        tag={"div"}
      >
        {content}
      </DOM>
    </div>
  );
}
