/**
 * @generated
 * @file Layout (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Layout
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Layout({
  classProp = "",
  colukmn2Class = "",
  column1,
  column1Class = "",
  column2,
  variant = "Stack",
}) {
  const _styleVariantMap = {
    Stack: "",
    "Stack Centered": "w-variant-313d4cb7-c103-55df-6f3a-ae2740861a50",
    "Auto Width": "w-variant-b21da2c5-e4d7-cf0a-65a0-d6581f6ad6dd",
    Columns: "w-variant-c017a6d6-d3f1-450b-7929-5369e2f6a6c9",
    "Columns 2/3": "w-variant-e7765a51-95eb-39f8-e25c-61e3900ef7d9",
    "Columns 2/3 Reversed": "w-variant-16eea105-69d8-fb54-70dd-5987d69644bc",
    "Columns Reversed": "w-variant-140e4ca0-4be0-f7e8-4972-ea0c1792e9ac",
    Breakout: "w-variant-26b01da2-470c-0cec-a39e-82f012fff67d",
    "Breakout Reversed": "w-variant-d3d266bd-6c56-23cf-78b8-338b31aacafb",
    Full: "w-variant-b5851c89-01ca-45c5-93ec-604840c79f59",
    "Full Reversed": "w-variant-8ecccd48-4ce7-b2f5-8e9d-0af339279e45",
    Contain: "w-variant-430302d3-e8fc-1ce3-56ef-1e0f315277de",
    "Contain Reversed": "w-variant-97ac1bb2-02c2-6b5b-5f11-4438ac75ee3e",
    Card: "w-variant-60f59cc2-1773-c719-7052-794afa19a64d",
    "Left Sticky": "w-variant-b8519cb5-1c50-7aca-6d3f-ef0019bf3931",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        class={classProp}
        className={`layout-wrapper ${_activeStyleVariant}`}
        id={""}
        tag={"div"}
      >
        <DOM className={`layout ${_activeStyleVariant}`} id={""} tag={"div"}>
          {column1}
          {column2}
        </DOM>
      </DOM>
    </div>
  );
}
