/**
 * @generated
 * @file Section (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { SectionSpace } from "./SectionSpace";

/**
 * Section
 *
 * Page Section
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function Section({
  background,
  content,
  customContainerClass = "container-large",
  paddingPaddingBottom = "Large",
  paddingPaddingTop = "Large",
  sectionId = "",
  theme = "Inherit",
}) {
  const _styleVariantMap = {
    Inherit: "",
    "Theme Light": "w-variant-06bfd700-a8fe-1bee-dfa2-248c38c5ee34",
    "Theme Dark": "w-variant-dfb2104f-deee-7b68-37bd-88633f0d3adf",
  };

  const _activeStyleVariant = _styleVariantMap[theme];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`section ${_activeStyleVariant}`}
        id={sectionId}
        tag={"section"}
      >
        {background}
        <SectionSpace variant={paddingPaddingTop} />
        {content}
        <SectionSpace variant={paddingPaddingBottom} />
      </Block>
    </div>
  );
}
