/**
 * @generated
 * @file SectionSpace (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * SectionSpace
 *
 * @see {@link https://detections-ai-new.design.webflow.com | Source site in Webflow}
 */
export function SectionSpace({ variant = "None" }) {
  const _styleVariantMap = {
    None: "",
    xSmall: "w-variant-74605af8-74da-5b76-8603-7c3e2e0a1d3e",
    Small: "w-variant-06539f70-5f1c-7b69-3356-58a6324ac143",
    Medium: "w-variant-ef9b3eac-2a11-f8cf-f392-b89b53acb212",
    Large: "w-variant-da9deacd-6bd2-1cf6-af5c-3a3c0552044d",
    "Page Top": "w-variant-6cb0206d-e10f-2d4b-08b6-0f8bb75211e1",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`g-section-space ${_activeStyleVariant}`} tag={"div"} />
    </div>
  );
}
